openapi: "3.0.n"
info:
  version: 1.0.0
  title: mixway API Documents
servers:
  - url: https://mixway.ekispert.jp
security:
  - ApiKeyAuth: []
paths:
  /v1/json/search/course/extreme:
    $ref: ./extreme.yml
  /v1/json/search/course/pattern:
    $ref: ./pattern.yml
